# Nombre de la aplicación
spring.application.name=backend

server.port=${PORT:8080}


#Cosas que debo cambiar si quiero tener un start mas rpaido en springboot
#Poner Swagger false
springdoc.swagger-ui.enabled=false
springdoc.api-docs.enabled=false

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui/index.html

spring.datasource.url=${DB_URL}

spring.datasource.username=${DB_USERNAME}

spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate

#Cosas que debo cambiar si quiero tener un start mas rpaido en springboot
#Cambiar sql udpate a validate
#spring.jpa.hibernate.ddl-auto=validate
# O incluso mejor  spring.jpa.hibernate.ddl-auto=none
spring.jpa.hibernate.ddl-auto=none
#spring.jpa.hibernate.ddl-auto=update

#Show Sql  false para mejorar
spring.jpa.show-sql=false
#spring.jpa.show-sql=true


#Cosas que debo cambiar si quiero tener un start mas rpaido en springboot
#Hikari puede ralentizar si falla conexión inicial:
spring.datasource.hikari.initialization-fail-timeout=0
#y opcional: spring.datasource.hikari.connection-timeout=5000
spring.datasource.hikari.connection-timeout=5000
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.data-source-properties.ssl=true
spring.datasource.hikari.data-source-properties.sslmode=require


#Mail
spring.mail.host=${MAIL_HOST}
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=${MAIL_HOST}


#Url properties
auth.google.client-id=${GOOGLE_ID}
auth.google.issuer=${GOOGLE_ISSUER}

app.frontend.reset-password-url=${FRONTEND_RESET_PASSWORD}

mail.from=${MAIL_USERNAME}

app.cors.allowed-origin=${CORS_ALLOWED}


#No cargar todos los beans al inicio solo cuando se necesitan
spring.main.lazy-initialization=true


# Configuración JWT
security.jwt.expiration.minutes = 61
security.jwt.secret.key=${JWT_SECRET_KEY}


